FROM microsoft/dotnet:2.0.4-runtime-jessie
LABEL maintainer="Michael Astrauckas"
WORKDIR /app
COPY build .
EXPOSE 5000
ENTRYPOINT ["dotnet", "Maa.MortgageCalculator.Endpoints.dll", "--urls=http://0.0.0.0:5000"]
