version: "3"

services:
  mywebmc-web-server:
    build: ./web-server/
    container_name: mywebmc-web-server
    image: mywebmc-web-server:v0.1.0
    depends_on:
      - mywebmc-api
      - mywebmc-static-web-server
    restart: 'always'
    ports:
      - '80:80'
    networks:
      - mywebmc

  mywebmc-api:
    build: ./api/
    container_name: mywebmc-api
    image: mywebmc-api:v0.2.0
    restart: 'always'
    networks:
      - mywebmc

  mywebmc-static-web-server:
    build: ./web/
    container_name: mywebmc-static-web-server
    image: mywebmc-static-web-server:v0.3.0
    restart: 'always'
    networks:
      - mywebmc

networks:
  mywebmc:
    external:
      name: mywebmc