env:
  node: true
  browser: true
  commonjs: true
  es6: true
parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
  - prettier/react
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - prettier
globals:
  __HOST_API__: true
rules:
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
    printWidth: 120
  indent:
    - error
    - 2
    - SwitchCase: 1
  curly:
    - error
    - all
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-extra-semi:
    - error
  no-console:
    - 0
  max-len:
    - error
    - code: 120
      ignoreUrls: true
